# create your custom drupal image here, based of official drupal
FROM drupal:8.6

RUN apt-get update \ && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*
#RUN apk update && apk add --no-cache git


WORKDIR /var/www/html/themes

RUN git clone --branch 8.x-4.x --single-branch --depth 1 https://git.drupalcode.org/project/bootstrap.git \
	&& chown -R www-data:www-data bootstrap


WORKDIR /var/www/html

